### ISSUE TITLE
[testing] add data-testid attribute to all components

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1001]
<sub>[Internal issue #320](https://github.ibm.com/Watson-IoT/pal-tracking/issues/320)</sub>

### Summary

To enable support of testing automation in applications that consume this library, we should provide a dedicated `data-testid` data attribute for each component. It should be placed on the containing element of each component as well as any pertinent sub sections. This attribute would be used in place of class or id selectors in testing automation for applications that consume this library.

| Prop Name | Attribute Name |
| - | - |
| `testId` | `data-testid` |

[Here's a link to Kent C. Dodd's blog with some reasoning for this naming convention](https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change). Additionally, it follows precedent set by React Native Web and the [React Testing Library that we use](https://testing-library.com/docs/dom-testing-library/api-queries#overriding-data-testid)

**Additional context**
For **exported, non-internal components** this should be configurable via a prop with a default prop of the component name.

```jsx
function ExportedComponent({ testId }) {
  return (
    <>
      <span data-testid={testId}>Example</span>
    </>
  );
}

ExportedComponent.propTypes = {
  testId: PropTypes.string,
};
ExportedComponent.defaultProps = {
  testId: 'ExportedComponent',
};
```

**Internal components** (such as those used internally in the table or elsewhere) should utilize any available id props to attempt to provide a unique value.

```jsx
function InternalTableCell({ tableId, columnId, rowId }) {
  return <td data-testid={`${tableId}-${columnId}-${rowId}`}>Example</td>;
}
```

High level checklist:
- [ ] Add attribute to all components
- [ ] Fix any usages we might have of improper naming, `test-ID` instead of `testId` or similar
- [ ] Update testing documentation to no longer state that "we working on this" but instead simply say "it's provided"
- [ ] Write test to ensure that these sections of the UI are always selectable  and do not break with changes.

**Comment by davidicus** [comment]
Things to consider when addressing Table test ids

>Hey @davidicus I meant to reply to this sooner.   Before this change I was using some css contains selector on the Styled component.   Right now, I'm basically doign this on code...w here I find at least 1 button in that section and then I use an xpath parent selector to move up to the container.  It's hacky but it works.   It would be nice if each table header row had a unique data-testid so that we could target the row and then child elements under it... [data-testid='columns-selector'] button so that we can get all button under that row.  (we do tests like verify that we have the same number of buttons as we do columns, etc).  In general for testing... It's helpful that different parts of a component can be targeted. For tables it's the header, toolbar, column manager, filter row, footer, pager, etc, etc.  Most of these, now, can be targed eitehr using id, class, data-testid... but some, like the column manager cannot.

**Comment by davidicus** [comment]
I think it makes sense for the project to adopt the strategy outlined as option number two in [this](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2446) RFC. This issue should become an epic to track both this issue as well as [this](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2374) other issue to align the usage the prop throughout the codebase.

**Comment by davidicus** [comment]
this epic is closed by the linked issues.
