### ISSUE TITLE
[node] v14 support

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1136]
[Internal Watson-IoT/pal-tracking#397](https://github.ibm.com/Watson-IoT/pal-tracking/issues/397)

### Summary

In October 2020 [Node 14 will move to Active LTS](https://nodejs.org/en/about/releases/). There are some benefits to upgrading.

![image](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)

List of items to complete:
- [x] update .nvmrc to `14`
- [x] update `engines` field in package.json
- [x] remove `full-icu` and related config/package.json env variables added in #1134 - v14 will build with `full-icu` included by default.
- [x] update any required dependencies to ensure the build and CI/Actions aren't interrupted (this will be the primary blocker here)
- [x] update any documentation that specifies the previous v12 version from #736 
- [x] ensure the `runtimeVersion` is updated in [`./.vscode/launch.json`](https://github.com/IBM/carbon-addons-iot-react/blob/master/.vscode/launch.json)
