### ISSUE TITLE
[Component Proposal] HotSpotEditorModal

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1753]
Part of issue #1741 

### What package is this for?

- [x] React
- [ ] Angular

### Summary

Dashboard card editor needs to have a support to add hotspots as part of the edit flow for ImageCards. 

Invision prototype found [here](https://ibm.invisionapp.com/share/QBO0RHWV9AE#/screens/319806855)

This feature will be delivered by a storybook example story and the following new components:
- ColorDropdown #1761 
- HotspotTooltipTab #1766
- HotspotDataSourceTab #1767
- HotspotTextStyleTab #1768
- TextHotspot #1861 
- ImageHotspots - add selecting and click creation of hotspots #1770

### Todos
The current [PR](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1891) contains a complete implementation but there are some issues still open based on feedback and realisations:

- [ ]  make tooltip stay open during hotspot edit (#1895)
- [ ] fix bug where scrollbar in modal causes incorrect position when creating a new hotspot (#1896)
- [ ] UX improvements to adding new hotspots (#1897)
- [ ] Add state handler unit tests (#1898)
- [ ] Improve how thresholds are managed in the cardConfiguration (#1899)
- [ ] Implement the updated design of the thresholds editing (#1769)
