### ISSUE TITLE
[MapCard] New Component

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2267]
This issue is an epic to track the development of the Map component. 

Will be completed when:
- [ ] component is build out and in storybook
- [ ] Documentation is written in its use. One for the root directory and also part of the story
- [ ] Passes a11y test scan in storybook as well as the IBM a11y unit test
- [ ] unit test are 80%+
- [ ] RTL testing has been done
- [ ] Confirm data tests IDs have been added to appropriate pieces for ease of targeting in unit test
- [ ] Design/ pattern audit
- [ ] Component is exported in index
