### ISSUE TITLE
[Repo] Write cypress test for components that need an actual DOM

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2313]
We are introducing cypress testing in order to do visual diff tests as well as test functionality that needs a real DOM to properly test. This issue is to address the following components's unit test thresholds exceptions. 

- [ ] 🤷‍♀️ TimeSeriesCard.jsx (Blocked see https://github.com/carbon-design-system/carbon-charts/issues/594)
- [ ] 🤷‍♀️ BarChartCard.jsx (Blocked see https://github.com/carbon-design-system/carbon-charts/issues/594)
- [ ] ☢️ 🤷‍♀️ DashboardEditor.jsx (Blocked see https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2152#issuecomment-807250836)

Please raise test coverage for the above components and remove the exceptions from our Jest config.
