### ISSUE TITLE
[Repo] Raise test coverage levels to acceptable levels

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#707]
Currently, small changes that are 100% test covered can shift the test thresholds and hold up PRs. There are several files that need to have more test written to bring them up to passable threshold levels to prevent this from happening. 

Goals are 
Functions to 82%
Branches to 80%
Set Coveralls to fail build if one PR drops us more than 2% in coverage

The offending Files:
- [x] ImageHotSpots.jsx
- [x] HeaderMenu.jsx
- [x] PageWizard.jsx
  - [x] StatefulPageWizard.jsx
- [x] CustomCard new code
- [x] AsyncTable.jsx
  - [x] MockApiClient.js
  - [x] asyncTableReducer.js
- [x] 🚫 WizardInline.jsx
  - [x] 🚫 WizardHeader.jsx
- [x] ListCard.jsx (Denny)
- [x] TableToolbar.jsx
- [ ] 🤷‍♀️ TimeSeriesCard.jsx (Blocked see https://github.com/carbon-design-system/carbon-charts/issues/594)
- [ ] 🤷‍♀️ BarChartCard.jsx (Blocked see https://github.com/carbon-design-system/carbon-charts/issues/594)
- [ ] ☢️ 🤷‍♀️ DashboardEditor.jsx (Blocked see https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2152#issuecomment-807250836)
- [x] FileDrop.jsx
- [x] thresholdsHelperFunctions.js
- [x] ImageCard.jsx
- [x] ImageUploader.jsx
- [x] 🚫 EditPage.jsx
- [x] 🚫 PageHero.jsx
- [x] 🚫 PageTitle.jsx
- [x] ColumnHeaderSelect.jsx
- [x] valueCardUtils.js
- [x] DashboardGrid.jsx
- [x] TableHeader.jsx
- [x] ColumnResize.jsx
- [x] FilterHeaderRow.jsx
- [x] RowActionsCell.jsx
- [x] RowActionsError.jsx
- [x] StatefulTable.jsx
- [x] CatalogContent.jsx
- [x] 🚫 Dashboard.jsx
  - [x] 🚫 CardRenderer.jsx  
- [x] StatefulTableDetailWizard.jsx
- [x] ☢️ ColorDropdown.jsx

---
Current exceptions to be fixed are listed in the jest.config.js

https://github.com/IBM/carbon-addons-iot-react/blob/06c9f7533439b949ecbb1b5fbe6ff9b159ee07e9/jest.config.js#L13-L86

These should be removed from both the exception list in the glob on L13, as well as the file-specific glob with the lower coverage amount

**Comment by tay1orjones** [comment]
It's been identified that part of this should also include a modification to track coverage on a per-component/file basis, instead of a global aggregate. 

We can achieve this by configuring glob patterns, instead of the default `global` in `./jest.config.js`. I'll issue a PR for this shortly which will highlight which components are lacking in coverage compared to our ideal of 80% coverage.

**Comment by tay1orjones** [comment]
Current exceptions are listed in the jest.config.js

https://github.com/IBM/carbon-addons-iot-react/blob/06c9f7533439b949ecbb1b5fbe6ff9b159ee07e9/jest.config.js#L13-L86

These should be removed from both the exception list in the glob on L13, as well as the file-specific glob with the lower coverage amount

**Comment by tay1orjones** [comment]
We've got quite a few exceptions in the jest config right now below the overall goal of 80% in every category on every component. Reopening

**Comment by jessieyan** [comment]
I'm working on tests for ListCard.

**Comment by jessieyan** [comment]
Now working on ColumnHeaderRow.jsx. Need to spend some time to understand how it works.

**Comment by tay1orjones** [comment]
Accidentally closed, reopening as we still have items with exceptions

**Comment by davidicus** [comment]
Since the majority of these test have been addressed and the remainder need cypress framework to complete I am closing and we will track the remainder in [this](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2313) issue
